import { TimelineEvent, UserProfile } from './types';

export const userProfile: UserProfile = {
  age: 28,
  height: '170 cm',
  weight: '83.1 kg',
  waist: '~36 inches',
  goal: 'Lose fat while maintaining/building muscle',
  work: 'Desk job',
  targetWeight: '75 kg',
  calories: '~1800–2000 kcal',
};

export const dailyTimeline: TimelineEvent[] = [
  {
    id: 'wake-water',
    time: '06:30 AM',
    type: 'water',
    title: 'Morning Hydration',
    description: 'Start your metabolism and hydrate after waking up.',
    items: ['500ml of water'],
  },
  {
    id: 'pre-workout',
    time: '07:00 AM',
    type: 'meal',
    title: 'Pre-workout Meal',
    description: 'Fuel up for your morning session.',
    items: [
      '2 whole eggs',
      'Chia seeds soaked in water',
      'Black coffee (optional)',
      '1 Nendra banana (steamed or ripe - excellent pre-workout carb)',
    ],
  },
  {
    id: 'workout-water',
    time: '08:00 AM',
    type: 'water',
    title: 'Workout Hydration',
    items: ['500ml water sipped throughout session'],
  },
  {
    id: 'post-workout',
    time: '09:00 AM',
    type: 'meal',
    title: 'Post-workout Breakfast',
    description: 'Muscle recovery and replenishment.',
    items: [
      '2 whole eggs + 3 egg whites',
      '2 slices whole wheat bread',
      '1 fruit (e.g., apple or berries)',
      '1 scoop whey protein',
      '5g glutamine',
    ],
    protein: '~45–50 g',
  },
  {
    id: 'mid-morning-water',
    time: '11:00 AM',
    type: 'water',
    title: 'Mid-morning Hydration',
    items: ['500ml of water'],
  },
  {
    id: 'pre-lunch-water',
    time: '01:00 PM',
    type: 'water',
    title: 'Pre-Lunch Hydration',
    items: ['500ml of water'],
  },
  {
    id: 'lunch',
    time: '01:30 PM',
    type: 'meal',
    title: 'Lunch',
    items: [
      '200g chicken, fish, or lean meat',
      '100–150g cooked rice',
      'Large salad and mixed vegetables',
      '1 fish oil capsule',
    ],
    protein: '~45 g',
  },
  {
    id: 'afternoon-water',
    time: '03:30 PM',
    type: 'water',
    title: 'Afternoon Hydration',
    items: ['500ml of water'],
  },
  {
    id: 'evening-snack',
    time: '05:00 PM',
    type: 'meal',
    title: 'Evening Yogurt Bowl',
    description: 'A daily serving of Greek yogurt helps with slow-digesting casein protein and probiotics for gut health.',
    items: [
      '1 bowl Greek yogurt or curd',
      'Handful of almonds (healthy fats)',
      '1/2 Nendra banana, Papaya, or Apple (budget-friendly fiber alternatives to berries)',
    ],
    protein: '~15–20 g',
  },
  {
    id: 'evening-water',
    time: '06:30 PM',
    type: 'water',
    title: 'Evening Hydration',
    items: ['500ml of water'],
  },
  {
    id: 'dinner',
    time: '08:00 PM',
    type: 'meal',
    title: 'Dinner',
    items: [
      '200g fish or chicken',
      '250–300g vegetables',
      '1–2 chapatis',
      '1 fish oil capsule',
    ],
    protein: '~40–45 g',
  },
  {
    id: 'night-water',
    time: '09:30 PM',
    type: 'water',
    title: 'Night Hydration',
    description: 'Final hydration before bed.',
    items: ['250ml of water'],
  },
];
